### PR TITLE
Improve ease of use, and performance.

### PR DESCRIPTION
**Pull request by airblast-dev**
I needed to pass around the card type to a generic function, where the function required Debug, and a few other traits implemented. After taking a look at the source code I thought a cleanup was in order.

Short list of what is done.
- I got rid of all of the clippy warnings.
- Derived, and/or implemented various traits that are often used, and that have zero cost to implement.
- Inlined smaller functions for performance reasons. 

Performance is slightly faster and much more consistent due to (I assume) cache hits.

- [x]  Ran `cargo check`
- [x]  Ran `cargo clippy`
- [x]  All tests ran successfully.

Edit: There isn't any change in public methods, so this should only modernize/optimize etc. internal methods.

### CODE REVIEW

**Comment by airblast-dev** [comment]
Let me know if there's anything that doesn't look right. I tried my best to modernize various parts, whilst not creating any breaking changes.

**Comment by valeriansaliou** [comment]
Thanks a ton! It looks all right, let me merge right now.

**Comment by valeriansaliou** [comment]
Released as `v2.4.0`. Thanks again for your work, had nothing to touch, it was spotless!

**Comment by airblast-dev** [comment]
Thanks, means a lot :smile:  Also don't forget to update the install guide in the readme.

**Pull request merged**
